config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: 'users/sessions',
             omniauth_callbacks: 'users/omniauth_callbacks' }

  resources :advertisements do
    resources :messages, except: [:edit, :update]
    resources :favorites, only: [:create]
  end

  resources :users do
    member do
      patch 'activate'
      get 'username'
    end

    resources :reviews, except: [:destroy, :show]
  end

  resources :favorites, only: [:destroy, :index]

  root to: 'welcome#index'
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :sender, foreign_key: :sender_id, class_name: User.name
  belongs_to :recipient, foreign_key: :recipient_id, class_name: User.name
  belongs_to :advertisement
  has_ancestry

  validates :body, presence: true

  enum status: [:inbox, :sent]

  scope :user_messages, ->(user) {
    joins(:sender).where(sender: user).or(joins(:sender).where(recipient: user))
  }
  
  scope :advertisement_messages, ->(advertisement) {
    joins(:advertisement).where(advertisement: advertisement)
  }
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :authenticate_user!, only: [ :new, :create, :destroy, :index, :show ]
  before_action :set_message, only: [ :destroy, :show ]
  before_action :set_advertisement, only: [ :index, :new, :create ]
  before_action :owners_only, only: [ :destroy ]
  before_action :request_username, only: [ :create ]

  include UsernameRequestable

  def index
    @messages = Message.advertisement_messages(@advertisement)
    @message = Message.new
  end

  def show
  end

  def new
    @message = Message.new(parent_id: params[:parent_id])
  end

  def create
    @message = Message.new(message_params)
    @message.sender = current_user
    @message.advertisement = @advertisement
    @message.recipient = User.find(@message.advertisement.user.id)

    respond_to do |format|
      if @message.save
        MessageMailer.new_message(@message).deliver
        unless params[:message][:parent_id] && params[:message][:parent_id].empty?
          format.html { redirect_to advertisement_messages_path(@advertisement), notice: "Message has been sent" }
        else
          format.js
        end
      else
        format.html { render :new, alert: "Message can'be created" }
      end
    end
  end

  def destroy
    @message.destroy
    redirect_to advertisement_messages_path, notice: "Message deleted"
  end

  private

  def message_params
    params.require(:message).permit(:title, :body, :recipient, :sender, :advertisement_id, :status, :parent_id)
  end

  def set_message
    @message = Message.find(params[:id])
  end

  def set_advertisement
    @advertisement = Advertisement.find(params[:advertisement_id])
  end

  def owners_only
    if current_user != @message.sender
      redirect_to advertisement_messages_path, alert: "You aren't the owner of this message!"
    end
  end


end

app/helpers/messages_helper.rb
module MessagesHelper
  def nested_messages(messages)
    messages.map do |message, sub_messages|
      render(message) + content_tag(:div, nested_messages(sub_messages))
    end.join.html_safe
  end
end

app/views/messages/_form.html.erb
<%= form_for @message, remote: true, url: advertisement_messages_path(@advertisement), html: { method: :post } do |f| %>
  <%= f.error_messages %>
  <%= f.hidden_field :parent_id %>
  <p>
    <%= f.label :body, "New Message" %><br />
    <%= f.text_area :body, rows: 8 %>
  </p>
  <p><%= f.submit "Post Message", class: 'btn' %></p>
<% end %>

app/views/messages/_message.html.erb
<div class="message">
  <div class="created_at"><%= message.created_at.strftime("%B %d, %Y") %> by
    <%= message.sender.username %>
  </div>
  <div class="content">
    <%= link_to message.body, advertisement_message_path(message.advertisement_id, message) %>
  </div>
  <div class="actions">
    <%= link_to "Reply", new_advertisement_message_path(parent_id: message) %> |
    <%= link_to "Destroy", advertisement_message_path(message.advertisement_id, message), confirm: "Are you sure?", method: :delete %>
  </div>
</div>

app/views/messages/create.js.erb
$('.nested_messages').append('<%=j render @message %>');
$('#message_body').val('');

app/views/messages/index.html.erb
<div class="row">
  <div class="col s3"></div>
  <div class="col s6 ">
    <h4>Messages</h4>
    <div class="nested_messages">
      <%= nested_messages @messages.arrange(order: :created_at) %>
    </div>
    <%= render "form" %>
  </div>
  <div class="col s3"></div>
</div>

app/views/messages/new.html.erb
<div class="row">
  <div class="col s3"></div>
  <div class="col s6">
    <h4>Reply</h4>

    <%= render @message.parent if @message.parent %>

    <%= render "form" %>

    <p><%= link_to "Back to Messages", advertisement_messages_path %></p>
  </div>
  <div class="col s3"></div>
</div>

app/views/messages/show.html.erb
<% title "Message" %>

<%= nested_messages @message.subtree.arrange(order: :created_at) %>

<p><%= link_to "Back to All Messages", advertisement_messages_path %></p>