config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: 'users/sessions',
             omniauth_callbacks: 'users/omniauth_callbacks' }

  resources :advertisements do
    resources :messages, except: [:edit, :update]
    resources :favorites, only: [:create]
  end

  resources :users do
    member do
      patch 'activate'
      get 'username'
    end

    resources :reviews, except: [:destroy, :show]
  end

  resources :favorites, only: [:destroy, :index]

  root to: 'welcome#index'
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :advertisement

  validates_uniqueness_of :user, scope: :advertisement

  scope :user_favorites, ->(user) {
    joins(:user).where(user: user)
  }
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  before_action :authenticate_user!
  before_action :owners_only, only: [ :destroy ]

  def index
    @favorites = Favorite.user_favorites(current_user)
  end

  def create
    @favorite = Favorite.new(favorite_params)
    @favorite.user = current_user
    @advertisement = Advertisement.find(@favorite.advertisement.id)
    if @favorite.save
      redirect_to advertisement_path(@advertisement), notice: 'Favorite has been saved'
    else
      redirect_to advertisement_path(@advertisement), alert: 'Ad is already in favorites'
    end
  end

  def destroy
    @favorite.destroy
    redirect_to favorites_path,  notice: 'Favorite has been removed'
  end

  private

  def favorite_params
    params.permit(:user_id, :advertisement_id)
  end

  def owners_only
    @favorite = Favorite.find(params[:id])
    if current_user != @favorite.user
      redirect_to root_path, alert: "You aren't the owner of this favorite!"
    end
  end
end

app/views/favorites/_favorite.html.erb
<tr>
  <% unless @user %>
    <td>
      <%= link_to favorite.advertisement.user.username, user_path(favorite.advertisement.user)%>
    </td>
  <% end %>
  <td><%= favorite.advertisement.title %></td>
  <td>
    <div class="ad-list">
      <%= link_to 'Show', advertisement_path(favorite.advertisement), class: "waves-effect waves-light btn"%>
      <%= link_to 'Delete', favorite_path(favorite), confirm: "Are you sure?", method: :delete, class: "waves-effect waves-light btn"%>
    </div>
  </td>
</tr>

app/views/favorites/index.html.erb
<h4> Favorites </h4>
<% if @favorites.count > 0 %>
  <table class="striped highlight centered">
    <thead>
      <tr>
          <th data-field="id">Username</th>
          <th data-field="name">Title</th>
          <th data-field="action">Action</th>
      </tr>
    </thead>

    <tbody>
      <%= render(@favorites) %>
    </tbody>
  </table>
<% else %>
  <p>No favorites added yet.</p>
<% end %>