config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: 'users/sessions',
             omniauth_callbacks: 'users/omniauth_callbacks' }

  resources :advertisements do
    resources :messages, except: [:edit, :update]
    resources :favorites, only: [:create]
  end

  resources :users do
    member do
      patch 'activate'
      get 'username'
    end

    resources :reviews, except: [:destroy, :show]
  end

  resources :favorites, only: [:destroy, :index]

  root to: 'welcome#index'
end

app/models/advertisement.rb
class Advertisement < ApplicationRecord
  belongs_to :user

  validates :title, presence: true
  validates :description, presence: true
  validates :user, presence: true
  validates :status, presence: true
  validates :ad_type, presence: true
  validates :price_cents, presence: true
  validates :amount, presence: true

  enum status: [:created, :published, :closed, :archived]
  enum ad_type: [:buy, :sell]

  monetize :price_cents

  scope :published_and_sell, -> {
    where(status: 'published', ad_type: 'sell')
  }

  scope :published_and_buy, -> {
    where(status: 'published', ad_type: 'buy')
  }

  scope :ordered_by_price, -> {
    order(price_cents: :desc)
  }

  scope :active_user, -> {
    joins(:user).where("users.status = 0")
  }

  scope :user_sell_ads, ->(user) {
    joins(:user).where(user: user, ad_type: 'sell')
  }

  scope :user_buy_ads, ->(user) {
    joins(:user).where(user: user, ad_type: 'buy')
  }

  scope :user_published_sell_ads, ->(user) {
    joins(:user).where(user: user, ad_type: 'sell', status: 'published')
  }
  
  scope :user_published_buy_ads, ->(user) {
    joins(:user).where(user: user, ad_type: 'buy', status: 'published')
  }

  class << self
    def published_sell
      published_and_sell.active_user.ordered_by_price
    end

    def published_buy
      published_and_buy.active_user.ordered_by_price
    end

    def user_published_sell(user)
      user_published_sell_ads(user).ordered_by_price
    end

    def user_published_buy(user)
      user_published_buy_ads(user).ordered_by_price
    end

    def user_all_sell(user)
      user_sell_ads(user).ordered_by_price
    end

    def user_all_buy(user)
      user_buy_ads(user).ordered_by_price
    end
  end


end

app/controllers/advertisements_controller.rb
class AdvertisementsController < ApplicationController
  before_action :authenticate_user!, only: [ :new, :create, :edit, :update, :destroy ]
  before_action :set_advertisement , only: [ :show, :edit, :update, :destroy ]
  before_action :owners_only, only: [ :edit, :update, :destroy ]
  before_action :request_username, only: [ :new ]
  rescue_from ActiveRecord::RecordNotFound, with: :invalid_ad

  include UsernameRequestable

  def index
    redirect_to root_path
  end

  def show
  end

  def new
    @advertisement = Advertisement.new
  end

  def create
    @advertisement = Advertisement.new(advertisement_params)
    @advertisement.user = current_user
    if @advertisement.save
      redirect_to advertisement_path(@advertisement), notice: 'Advertisement has been created'
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @advertisement.update(advertisement_params)
      redirect_to advertisement_path(@advertisement), notice: 'Advertisement has been updated'
    else
      render :edit
    end
  end

  def destroy
    if @advertisement.update(status: :archived)
      redirect_to advertisements_path, notice: 'Advertisement archived'
    else
      redirect_to advertisements_path, alert: 'There was a problem archiving advertisement'
    end
  end

  private

  def advertisement_params
    params.require(:advertisement).permit(:title, :description, :price_cents, :status, :user, :ad_type, :amount)
  end

  def set_advertisement
    @advertisement = Advertisement.find(params[:id])
  end

  def owners_only
    if current_user != @advertisement.user
      redirect_to advertisements_path, alert: "You aren't the owner of this advertisement!"
    end
  end

  def invalid_ad
    redirect_to root_path, alert: "Ad doesn't exist"
  end
end

app/views/advertisements/_advertisement.html.erb
<tr>
  <% unless @user %>
    <td>
      <%= link_to advertisement.user.username, user_path(advertisement.user)%>
    </td>
  <% end %>
  <td><%= advertisement.title %></td>
  <td><%= number_to_currency(advertisement.price_cents) %></td>
  <td><%= advertisement.amount %></td>
  <td>
    <div class="ad-list">
      <%= link_to 'Show', advertisement_path(advertisement), class: "waves-effect waves-light btn"%>
    </div>
  </td>
</tr>

app/views/advertisements/edit.html.erb
<div class="row edit-ad">
  <div class="col s3"></div>
  <div class="col s6">
    <h2>Edit advertisement</h2>
  <%= form_for @advertisement do |f| %>

    <% if @advertisement.errors.full_messages.any? %>
      <% @advertisement.errors.full_messages.each do |error_message| %>
        <%= error_message %> <br />
      <% end %>
    <% end %>

    <%= f.label :title, "Title" %><br />
    <%= f.text_field :title %>
    <%= f.label :description, "Description" %><br />
    <%= f.text_area :description %>
    <%= f.label :price_cents, "Price" %><br />
    <%= f.text_field :price_cents %>
    <%= f.label :amount, "Amount" %><br />
    <%= f.text_field :amount %>
    <%= f.label :status, "Status" %><br />
    <%= f.select :status, options_for_select(Hash[Advertisement.statuses.map { |k,v| [ k.split('_').first.capitalize, k ]}], @advertisement.status) %>
    <%= f.label :ad_type, "Type" %><br />
    <%= f.select :ad_type, options_for_select(Hash[Advertisement.ad_types.map { |k,v| [ k.split('_').first.capitalize, k ]}], @advertisement.ad_type) %>

    <%= f.submit 'Edit Advertisement', class: 'btn' %>
  <% end %>
  </div>
  <div class="col s3"></div>
</div>

app/views/advertisements/index.html.erb
<ul class="collection with-header">
  <li class="collection-header"><h4>Advertisements</h4></li>
  <% @advertisements.each do |ad| %>
    <li class="collection-item"><div><%= ad.title %>
    <%= link_to advertisement_path(ad), class: "secondary-content" do%>
      <i class="material-icons">info_outline</i>
    <% end %>
    </div></li>
  <% end%>
</ul>

<% if @advertisements.count == 0 %>
  <h1>No advertisements published yet.</h1>
<% end%>

app/views/advertisements/new.html.erb
<div class="row edit-ad">
  <div class="col s3"></div>
  <div class="col s6">
  <h2>New advertisement</h2>
  <%= form_for @advertisement do |f| %>

    <% if @advertisement.errors.full_messages.any? %>
      <% @advertisement.errors.full_messages.each do |error_message| %>
        <%= error_message %> <br />
      <% end %>
    <% end %>

    <%= f.label :title, "Title" %><br />
    <%= f.text_field :title %>
    <%= f.label :description, "Description" %><br />
    <%= f.text_area :description %>
    <%= f.label :price_cents, "Price" %><br />
    <%= f.text_field :price_cents %>
    <%= f.label :amount, "Amount" %><br />
    <%= f.text_field :amount %>
    <%= f.label :status, "Status" %><br />
    <%= f.select :status, options_for_select(Hash[Advertisement.statuses.map { |k,v| [ k.split('_').first.capitalize, k ]}], @advertisement.status) %>
    <%= f.label :ad_type, "Type" %><br />
    <%= f.select :ad_type, options_for_select(Hash[Advertisement.ad_types.map { |k,v| [ k.split('_').first.capitalize, k ]}], @advertisement.ad_type) %>

    <%= f.submit 'Create Advertisement', class: 'btn' %>
  <% end %>
  </div>
  <div class="col s3"></div>
</div>

app/views/advertisements/show.html.erb
<div class="row">
  <div class="col s12">
    <% if @advertisement.errors.full_messages.any? %>
      <% @advertisement.errors.full_messages.each do |error_message| %>
        <%= error_message %> <br />
      <% end %>
    <% end %>
    <div class="card">
      <div class="card-content">
        <span class="card-title"><%= @advertisement.title %></span>
        <span class="card-content">
          <blockquote>
            <p><b> User:   </b> <%= @advertisement.user.username %></p>
            <p><b> Price:  </b><%= number_to_currency(@advertisement.price_cents) %></p>
            <p><b> Amount: </b><%= @advertisement.amount %> </p>
            <p><b> Type:   </b><%= @advertisement.ad_type.capitalize %></p>
            <p><b> Status: </b><%= @advertisement.status.capitalize %></p>
          </blockquote>
        </span>
        <div class="card-content">
          <b>Description: </b><%= @advertisement.description %>
        </div>
      </div>
      <div class="card-action light-blue darken-4">
      <% if current_user && current_user.username == @advertisement.user.username %>
        <%= link_to edit_advertisement_path(@advertisement) do %>
          <i class="small material-icons" title="Edit">mode_edit</i>
        <% end %>
        <%= link_to advertisement_path(@advertisement), data: { confirm: "Are you sure?" }, method: :delete do %>
          <i class="small material-icons" title="Delete">delete</i>
        <% end %>
      <% else %>
        <!-- <%= link_to 'Send New Message', new_advertisement_message_path(@advertisement) %> -->
      <% end %>
      <%= link_to advertisement_messages_path(@advertisement) do %>
        <i class="small material-icons" title="Messages">message</i>
      <% end %>
      <%= link_to advertisement_favorites_path(@advertisement), method: :post do %>
        <i class="small material-icons" title="Save to favorites">system_update_alt</i>
      <% end %>
      </div>
    </div>
  </div>
</div>