config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: 'users/sessions',
             omniauth_callbacks: 'users/omniauth_callbacks' }

  resources :advertisements do
    resources :messages, except: [:edit, :update]
    resources :favorites, only: [:create]
  end

  resources :users do
    member do
      patch 'activate'
      get 'username'
    end

    resources :reviews, except: [:destroy, :show]
  end

  resources :favorites, only: [:destroy, :index]

  root to: 'welcome#index'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ads</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag    "https://fonts.googleapis.com/icon?family=Material+Icons" %>
  </head>

  <body>
    <header>
      <nav>
        <div class="nav-wrapper">
          <%= link_to 'Exchange Today', root_path, class: "brand-logo"%>
          <ul id="nav-mobile" class="right hide-on-med-and-down">
            <% if current_user %>
              <li><%= link_to favorites_path do %>
                <i class="small material-icons" title="Favorites">turned_in</i>
              <% end %></li>
              <li><%= link_to new_advertisement_path do %>
                <i class="small material-icons" title="New Advertisement">note_add</i>
              <% end %></li>
              <li><a class='dropdown-button' data-beloworigin="true" href='#' data-activates='profile'><%= current_user.username %></a></li>
              <ul id='profile' class='dropdown-content'>
                <li><%= link_to 'Profile', user_path(current_user)%></li>
                <li><%= link_to 'Logout', destroy_user_session_path, method: :delete %></li>
              </ul>
              <% if current_user.picture.to_s.empty? %>
                <li><i class="large material-icons">perm_identity</i></li>
              <% else %>
                <li><%= image_tag current_user.picture.to_s, class: 'img-circle' %></li>
              <% end %>
            <% else %>
              <li><%= link_to 'Log in', new_user_session_path %></li>
            <% end %>
          </ul>
        </div>
      </nav>

      <% if notice %>
        <div class="card green lighten-5">
          <div class="card-content green-text">
            <%= notice %>
          </div>
        </div>
      <% end %>

      <% if alert %>
        <div class="card red lighten-5">
          <div class="card-content red-text">
            <%= alert %>
          </div>
        </div>
      <% end %>
    </header>

  <main>
    <div class="container">
      <%= yield %>
    </div>
  </main>

  <footer class="page-footer">
    <!-- <div class="container">
      <div class="row">
        <div class="col l6 s12">
          <h5 class="white-text">Footer Content</h5>
          <p class="grey-text text-lighten-4">You can use rows and columns here to organize your footer content.</p>
        </div>
        <div class="col l4 offset-l2 s12">
          <h5 class="white-text">Links</h5>
          <ul>
            <li><a class="grey-text text-lighten-3" href="#!">Link 1</a></li>
          </ul>
        </div>
      </div>
    </div> -->
    <div class="footer-copyright">
      <div class="container">
      © 2016 Copyright Text
      <a class="grey-text text-lighten-4 right" href="#!">More Links</a>
      </div>
    </div>
  </footer>
  <script>
    $(document).ready(function() {
        $('select').material_select();
    });
  </script>
  </body>
</html>